/** String event types for JobActivityEvent — avoid Prisma enum churn. */

export const JobActivityEventType = {
  JOB_CREATED: "JOB_CREATED",
  JOB_STATUS_CHANGED: "JOB_STATUS_CHANGED",
  JOB_TASK_STATUS_UPDATED: "JOB_TASK_STATUS_UPDATED",
  JOB_TASK_BLOCKED: "JOB_TASK_BLOCKED",
  JOB_TASK_COMPLETED: "JOB_TASK_COMPLETED",
  SCHEDULED_WORK_CREATED: "SCHEDULED_WORK_CREATED",
  SCHEDULED_WORK_RESCHEDULED: "SCHEDULED_WORK_RESCHEDULED",
  SCHEDULED_WORK_CANCELED: "SCHEDULED_WORK_CANCELED",
  JOB_EVIDENCE_PROMOTED: "JOB_EVIDENCE_PROMOTED",
  JOB_EVIDENCE_ACCEPTED: "JOB_EVIDENCE_ACCEPTED",
  JOB_EVIDENCE_REJECTED: "JOB_EVIDENCE_REJECTED",
  JOB_TASK_COMPLETION_REQUIREMENTS_UPDATED: "JOB_TASK_COMPLETION_REQUIREMENTS_UPDATED",
  JOB_TASK_COMPLETED_WITH_EVIDENCE_OVERRIDE: "JOB_TASK_COMPLETED_WITH_EVIDENCE_OVERRIDE",
} as const;

export type JobActivityEventTypeName = (typeof JobActivityEventType)[keyof typeof JobActivityEventType];
