export const QuoteActivityEventType = {
  QUOTE_DRAFT_CREATED: "QUOTE_DRAFT_CREATED",
  QUOTE_UPDATED: "QUOTE_UPDATED",
  QUOTE_LINE_ADDED: "QUOTE_LINE_ADDED",
  QUOTE_LINE_UPDATED: "QUOTE_LINE_UPDATED",
  QUOTE_LINE_REMOVED: "QUOTE_LINE_REMOVED",
  QUOTE_LINE_EXECUTION_STAGE_ADDED: "QUOTE_LINE_EXECUTION_STAGE_ADDED",
  QUOTE_LINE_EXECUTION_STAGE_UPDATED: "QUOTE_LINE_EXECUTION_STAGE_UPDATED",
  QUOTE_LINE_EXECUTION_STAGE_REMOVED: "QUOTE_LINE_EXECUTION_STAGE_REMOVED",
  QUOTE_LINE_EXECUTION_TASK_ADDED: "QUOTE_LINE_EXECUTION_TASK_ADDED",
  QUOTE_LINE_EXECUTION_TASK_UPDATED: "QUOTE_LINE_EXECUTION_TASK_UPDATED",
  QUOTE_LINE_EXECUTION_TASK_COMPLETED: "QUOTE_LINE_EXECUTION_TASK_COMPLETED",
  QUOTE_TASK_ADDED: "QUOTE_TASK_ADDED",
  QUOTE_TASK_UPDATED: "QUOTE_TASK_UPDATED",
  QUOTE_TASK_COMPLETED: "QUOTE_TASK_COMPLETED",
  QUOTE_ASSUMPTION_ADDED: "QUOTE_ASSUMPTION_ADDED",
  QUOTE_ASSUMPTION_UPDATED: "QUOTE_ASSUMPTION_UPDATED",
  QUOTE_ASSUMPTION_REMOVED: "QUOTE_ASSUMPTION_REMOVED",
  QUOTE_PREVIEWED: "QUOTE_PREVIEWED",
  QUOTE_MARKED_READY: "QUOTE_MARKED_READY",
  /** Proposal finalized and transactional email accepted by provider (payload includes recipient + provider ids). */
  QUOTE_EMAIL_DELIVERY_SENT: "QUOTE_EMAIL_DELIVERY_SENT",
  /** Email or portal-link step failed after quote was already marked SENT (payload includes sanitized error). */
  QUOTE_EMAIL_DELIVERY_FAILED: "QUOTE_EMAIL_DELIVERY_FAILED",
  QUOTE_SENT: "QUOTE_SENT",
  QUOTE_ACCEPTED: "QUOTE_ACCEPTED",
  QUOTE_ACTIVATED: "QUOTE_ACTIVATED",
  QUOTE_STATUS_CHANGED: "QUOTE_STATUS_CHANGED",
  QUOTE_WORK_TEMPLATE_LINE_SAVED: "QUOTE_WORK_TEMPLATE_LINE_SAVED",
  QUOTE_WORK_TEMPLATE_STAGE_SAVED: "QUOTE_WORK_TEMPLATE_STAGE_SAVED",
  QUOTE_WORK_TEMPLATE_TASK_SAVED: "QUOTE_WORK_TEMPLATE_TASK_SAVED",
  QUOTE_WORK_TEMPLATE_LINE_INSERTED: "QUOTE_WORK_TEMPLATE_LINE_INSERTED",
  QUOTE_WORK_TEMPLATE_STAGE_INSERTED: "QUOTE_WORK_TEMPLATE_STAGE_INSERTED",
  QUOTE_WORK_TEMPLATE_TASK_INSERTED: "QUOTE_WORK_TEMPLATE_TASK_INSERTED",
} as const;

export type QuoteActivityEventTypeName =
  (typeof QuoteActivityEventType)[keyof typeof QuoteActivityEventType];
